### ISSUE TITLE
[Error] VisualCaptcha isn't shown on login-pulldown

### ISSUE THREAD

**Issue by chimcen** [e107inc/visualcaptcha#1]
Hi,

i'm using currently the latest github version of e107v2 and tried out your plugin.
But it wont be shown on my login-pulldown - biut ist active bacause when i try to login i got the message my code isn't correct...
First i thought its might be a theme related problem and i've tried bootstrap3 theme also - but the same result.
![visualcaptchaproblem](https://cloud.githubusercontent.com/assets/22658487/21314563/0a4f7af8-c5f8-11e6-98ad-9da058e95720.JPG)

When deactivate (not uninstall) the visualcpatcha plugin i got the old securitycaptcha back...
![visualcaptchaproblem1](https://cloud.githubusercontent.com/assets/22658487/21314592/31f7f896-c5f8-11e6-94ae-50ec200bef01.JPG)

Btw. tried this on my local testing site (using xampp) - but this shouldn't be a difference...

**Comment by lonalore** [comment]
Try to clear cache, and rescan your plugin directories.

**Comment by lonalore** [comment]
If it does not help:
1, Update your e107 to the latest Github files
2, Make sure your plugin folder is 'visualcaptcha', and not 'visualcaptcha-master'
3, Make sure 'visualCaptcha Frontend' library is available (check the green tick on 'e107_admin/prefs.php#nav-core-prefs-javascript' page)

**Comment by chimcen** [comment]
- cleared e107 cache & browser cache
- rescanned plugin dirs
- e107v2 is latest from github
- library is loaded
![library](https://cloud.githubusercontent.com/assets/22658487/21315315/db9c5330-c5fb-11e6-8be1-e64c96f3ebc7.JPG)

Same problem as before... :(
Tried login.php - also the same...

**Comment by Jimmi08** [comment]
Just installed on localhost php 5.5 xampp.  No problems.  Try to check your console.

**Comment by lonalore** [comment]
Enable debug mode, and check your browser's console, as @Jimmi08 suggested. You should be able to see error message in Ajax response.

**Comment by lonalore** [comment]
Btw. Did you check your plugin folder? If you downloaded visualcaptcha from Github, you have to rename the folder from 'visualcaptcha-master' to 'visualcaptcha'.

**Comment by chimcen** [comment]
Didn't find the settings for activate the debugger...
But yes, there is an error in my browsers conole (chrome) - see the logfile:

[localhost-1482157444847.log.txt](https://github.com/e107inc/visualcaptcha/files/661293/localhost-1482157444847.log.txt)

yes - i know the things with the foldername from git versions...

**Comment by lonalore** [comment]
Ahhh, you must enable 'php_openssl' extension on your server.

**Comment by Jimmi08** [comment]
@chimcen  For future using (second one is Firefox extension.):
![image](https://cloud.githubusercontent.com/assets/5429548/21316459/288bfaa6-c601-11e6-96e8-6e582dc7df27.png)

![image](https://cloud.githubusercontent.com/assets/5429548/21316482/3d910644-c601-11e6-99e3-372d12f85b32.png)

You can use define('e_DEBUG',true); in e107_config.php file too.

**Comment by lonalore** [comment]
@chimcen here is a description for enabling openssl extension on xampp: 
http://stackoverflow.com/a/11040496/2416835

**Comment by lonalore** [comment]
Ohh @CaMer0n has been faced with this issue: https://github.com/emotionLoop/visualCaptcha-PHP/issues/23 :D

**Comment by chimcen** [comment]
yes, openssl was the problem - thank you lonalore... now it works. thank you - btw. thank you (and cameron) for this awesome plugin! :)

@Jimmi08 - thank you - i got it allready using the e107v2 wiki... ( [http://e107.org/developer-manual/getting-started/debugging](url) )
