### ISSUE TITLE
visualcaptcha returns incorrect code using 'contact us'

### ISSUE THREAD

**Issue by martyshep** [e107inc/visualcaptcha#5]
When a guest uses Contact Us, visualcaptcha always returns 'invalid code' regardless of amount of icons specified in visualcaptcha config. Reset password works ok, it's just on contact us.

Running version 2.1.6(Git)

**Comment by martyshep** [comment]
![image](https://cloud.githubusercontent.com/assets/15772899/25377467/925bc6c6-299f-11e7-8744-1759f03fd142.png)

**Comment by Norwayman** [comment]
I can confirm this. And also for me the capcha is rendered two times.
![doublecisualcapcha](https://user-images.githubusercontent.com/1757346/28540336-9f649f92-707a-11e7-9ebd-4dae3987ae32.JPG)

**Comment by aducom** [comment]
This issue still applies in the current version of E107 in Git (2.3.0). The only solution is to unset the visual captcha and the standard image code appears again. In the preferences, there is an option to tell where you want the image code to appear, but the contact page is missing. I think that the image is overwritten, but the original code is not adapted causing the messagebox.

**Comment by aducom** [comment]
The issue is still there in v2.3.1 (git)

**Comment by Moc** [comment]
@aducom Should be fixed now with the latest e107 core files from Github. Please test and let us know.
